development:
  adapter: postgresql
  database: frugalistas_project_dev
  host: localhost
  pool: 5
  timeout: 5000
  username: tbuckley
  password:

test:
  adapter: postgresql
  database: frugalistas_project_test
  host: localhost
  pool: 5
  timeout: 5000
  username: tbuckley
  password:

production:
  adapter: postgresql
  database: frugalistas_project_prods
  host: localhost
  pool: 5
  timeout: 5000
  username: tbuckley
  password: